// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqtyatwvjmsgzywifhvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxdHlhdHd2am1zZ3p5d2lmaHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTE1MzksImV4cCI6MjA2MjM2NzUzOX0.E7a1CcqT46JONORbGlfTbSSYHc0wXpwy5MvKQr2vGQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);